{{- range $key, $value := .Values.apigroups }}
{{- range $namespacePattern := $.Values.namespace_patterns }}
{{ if eq ( $value.enabled | toString) "true" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ printf $namespacePattern $value.name | quote }}
  labels:
    argocd.argoproj.io/managed-by: {{ $.Values.application_gitops_namespace }}
    {{- include "common.labels" $ | nindent 4 }}
    {{- if $value.labels -}}
    {{ toYaml .labels | nindent 4 }}
    {{- end }}
    {{- if $value.additional_settings }}
    {{- with $value.additional_settings }}
    {{- if .podsecurity_audit }}
    pod-security.kubernetes.io/audit: {{ .podsecurity_audit }}
    {{- end }}
    {{- if .podsecurity_warn }}
    pod-security.kubernetes.io/warn: {{ .podsecurity_warn }}
    {{- end }}
    {{- if .podsecurity_enforce }}
    pod-security.kubernetes.io/enforce: {{ .podsecurity_enforce }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- if $value.project_size }}
    namespace-size: {{ $value.project_size | quote }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $value.syncwave | default "1" | quote }}
{{- end }}
{{- end }}
{{- end }}
