{{- range $key, $value := .Values.apigroups }}
{{- range $namespacePattern := $.Values.namespace_patterns }}
{{ if eq ( $value.enabled | toString) "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: status-checker-role
  namespace: {{ printf $namespacePattern $value.name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    argocd.argoproj.io/sync-wave: {{ $value.syncwave | default "2" | quote }}
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
      - installplans
      - subscriptions
      - subscription
    verbs:
      - get
      - list
      - patch
{{- end }}
{{- end }}
{{- end }}